name: menu_bar
description: A customizable application menu bar with submenus for your Flutter Desktop apps.
version: 1.0.0
repository: https://github.com/iakmds/menu_bar
topics:
 - desktop
 - menu

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  material_ui: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
   sdk: flutter
