name: menu_bar
description: A customizable application menu bar with submenus for your Flutter Desktop apps.
version: 0.5.1
repository: https://github.com/iakmds/menu_bar

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
